#!/bin/bash

set -e

if test ! -d ".git" ; then
 echo Must be run from the base directory of the GIT repository
 exit
fi

################


if git diff --cached | egrep -2 '^(old.mode|new.mode)' ; then
 echo 'Please do not change mode of files'
 exit 1
fi

############

# Array to track all temporary directories
tmpdirs=()

# Cleanup function with safety checks
cleanup() {
    for tmpdir in "${tmpdirs[@]}"; do
        # Safety checks before deletion
        if test -z "$tmpdir" ; then
            continue
        fi
        if ! test -d "$tmpdir" ; then
            echo "Disappeared $tmpdir"
            continue
        fi

        # Check if it's in /tmp using case pattern matching (POSIX-compliant)
        case "$tmpdir" in
            /tmp/*)
                rm -rf "$tmpdir"
                echo "Cleaned up $tmpdir"
                ;;
            *)
                echo "WARNING: temp dir is not in /tmp, refusing to delete: $tmpdir" >&2
                ;;
        esac
    done
}

# Set up trap to cleanup on exit or error
trap "echo PANIC CLEANUP ; cleanup" ERR HUP INT QUIT TERM


######### prepare test dir


t=`mktemp -d`
# Add to cleanup list
tmpdirs+=("${t}")

test -d $t

echo ============= TEST IN $t


git archive HEAD | ( cd $t ; tar xf - )


git diff --cached | ( cd $t ; patch -p1 )

######### hack

origdir=$(realpath . )

test -L "$t"/coldoc_tasks/wrap_lockfile.py
rm     "$t"/coldoc_tasks/wrap_lockfile.py
cp -av  "$origdir"/sub/wrap_lockfile/wrap_lockfile.py -t "$t"/coldoc_tasks/

########## flake, pylint

pushd $t

flake8 .  --select=E9,F63,F7,F82

for s in unittests/test*py ; do
    if test -f "$s" ; then
	python3 "$s" -v
    fi
done

# I hate pytest

popd

cleanup
