#!/bin/bash

set -e

if test ! -d ".git" ; then
 echo Must be run from the base directory of the GIT repository
 exit
fi

################


if git diff --cached | egrep -2 '^(old.mode|new.mode)' ; then
 echo 'Please do not change mode of files'
 exit 1
fi



######### prepare test dir


t=`mktemp -d`

test -d $t

#trap "rm -fr \"$\"t" EXIT ERR HUP INT QUIT TERM

git archive HEAD | ( cd $t ; tar xf - )


git diff --cached | ( cd $t ; patch -p1 )

######### hack

origdir=$(realpath . )

test -L "$t"/coldoc_tasks/wrap_lockfile.py
rm     "$t"/coldoc_tasks/wrap_lockfile.py
cp -av  "$origdir"/sub/wrap_lockfile/wrap_lockfile.py -t "$t"/coldoc_tasks/

########## flake, pylint

pushd $t

flake8 .  --select=E9,F63,F7,F82

for s in unittests/test*py ; do
    if test -f "$s" ; then
	python3 "$s" -v
    fi
done

# I hate pytest

echo You should: rm -fr "$t"

popd
